package Hibernate;
// Generated Apr 18, 2013 4:15:57 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * BandsperfestivalId generated by hbm2java
 */
public class BandsperfestivalId  implements java.io.Serializable {


     private int festId;
     private int bandId;
     private Date datum;

    public BandsperfestivalId() {
    }

    public BandsperfestivalId(int festId, int bandId, Date datum) {
       this.festId = festId;
       this.bandId = bandId;
       this.datum = datum;
    }
   
    public int getFestId() {
        return this.festId;
    }
    
    public void setFestId(int festId) {
        this.festId = festId;
    }
    public int getBandId() {
        return this.bandId;
    }
    
    public void setBandId(int bandId) {
        this.bandId = bandId;
    }
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BandsperfestivalId) ) return false;
		 BandsperfestivalId castOther = ( BandsperfestivalId ) other; 
         
		 return (this.getFestId()==castOther.getFestId())
 && (this.getBandId()==castOther.getBandId())
 && ( (this.getDatum()==castOther.getDatum()) || ( this.getDatum()!=null && castOther.getDatum()!=null && this.getDatum().equals(castOther.getDatum()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getFestId();
         result = 37 * result + this.getBandId();
         result = 37 * result + ( getDatum() == null ? 0 : this.getDatum().hashCode() );
         return result;
   }   


}


