package Hibernate;
// Generated Apr 18, 2013 4:15:57 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Campings generated by hbm2java
 */
public class Campings  implements java.io.Serializable {


     private Integer campId;
     private String campAdres;
     private int campCap;
     private Set festivalses = new HashSet(0);
     private Set facpercamps = new HashSet(0);

    public Campings() {
    }

	
    public Campings(String campAdres, int campCap) {
        this.campAdres = campAdres;
        this.campCap = campCap;
    }
    public Campings(String campAdres, int campCap, Set festivalses, Set facpercamps) {
       this.campAdres = campAdres;
       this.campCap = campCap;
       this.festivalses = festivalses;
       this.facpercamps = facpercamps;
    }
   
    public Integer getCampId() {
        return this.campId;
    }
    
    public void setCampId(Integer campId) {
        this.campId = campId;
    }
    public String getCampAdres() {
        return this.campAdres;
    }
    
    public void setCampAdres(String campAdres) {
        this.campAdres = campAdres;
    }
    public int getCampCap() {
        return this.campCap;
    }
    
    public void setCampCap(int campCap) {
        this.campCap = campCap;
    }
    public Set getFestivalses() {
        return this.festivalses;
    }
    
    public void setFestivalses(Set festivalses) {
        this.festivalses = festivalses;
    }
    public Set getFacpercamps() {
        return this.facpercamps;
    }
    
    public void setFacpercamps(Set facpercamps) {
        this.facpercamps = facpercamps;
    }




}


