package Hibernate;
// Generated Apr 18, 2013 4:15:57 PM by Hibernate Tools 3.2.1.GA



/**
 * Facpercamp generated by hbm2java
 */
public class Facpercamp  implements java.io.Serializable {


     private FacpercampId id;
     private Faciliteiten faciliteiten;
     private Campings campings;
     private int aantal;

    public Facpercamp() {
    }

    public Facpercamp(FacpercampId id, Faciliteiten faciliteiten, Campings campings, int aantal) {
       this.id = id;
       this.faciliteiten = faciliteiten;
       this.campings = campings;
       this.aantal = aantal;
    }
   
    public FacpercampId getId() {
        return this.id;
    }
    
    public void setId(FacpercampId id) {
        this.id = id;
    }
    public Faciliteiten getFaciliteiten() {
        return this.faciliteiten;
    }
    
    public void setFaciliteiten(Faciliteiten faciliteiten) {
        this.faciliteiten = faciliteiten;
    }
    public Campings getCampings() {
        return this.campings;
    }
    
    public void setCampings(Campings campings) {
        this.campings = campings;
    }
    public int getAantal() {
        return this.aantal;
    }
    
    public void setAantal(int aantal) {
        this.aantal = aantal;
    }




}


