package Hibernate;
// Generated Apr 18, 2013 4:15:57 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Geregistreerdegebruikers generated by hbm2java
 */
public class Geregistreerdegebruikers  implements java.io.Serializable {


     private Integer gebrId;
     private String gebrNaam;
     private String gebrAdres;
     private Date gebrGebDat;
     private String gebrPaswoord;
     private Set ticketses = new HashSet(0);

    public Geregistreerdegebruikers() {
    }

	
    public Geregistreerdegebruikers(String gebrNaam, String gebrAdres, Date gebrGebDat, String gebrPaswoord) {
        this.gebrNaam = gebrNaam;
        this.gebrAdres = gebrAdres;
        this.gebrGebDat = gebrGebDat;
        this.gebrPaswoord = gebrPaswoord;
    }
    public Geregistreerdegebruikers(String gebrNaam, String gebrAdres, Date gebrGebDat, String gebrPaswoord, Set ticketses) {
       this.gebrNaam = gebrNaam;
       this.gebrAdres = gebrAdres;
       this.gebrGebDat = gebrGebDat;
       this.gebrPaswoord = gebrPaswoord;
       this.ticketses = ticketses;
    }
   
    public Integer getGebrId() {
        return this.gebrId;
    }
    
    public void setGebrId(Integer gebrId) {
        this.gebrId = gebrId;
    }
    public String getGebrNaam() {
        return this.gebrNaam;
    }
    
    public void setGebrNaam(String gebrNaam) {
        this.gebrNaam = gebrNaam;
    }
    public String getGebrAdres() {
        return this.gebrAdres;
    }
    
    public void setGebrAdres(String gebrAdres) {
        this.gebrAdres = gebrAdres;
    }
    public Date getGebrGebDat() {
        return this.gebrGebDat;
    }
    
    public void setGebrGebDat(Date gebrGebDat) {
        this.gebrGebDat = gebrGebDat;
    }
    public String getGebrPaswoord() {
        return this.gebrPaswoord;
    }
    
    public void setGebrPaswoord(String gebrPaswoord) {
        this.gebrPaswoord = gebrPaswoord;
    }
    public Set getTicketses() {
        return this.ticketses;
    }
    
    public void setTicketses(Set ticketses) {
        this.ticketses = ticketses;
    }




}


