package Hibernate;
// Generated Apr 18, 2013 4:15:57 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tickettypes generated by hbm2java
 */
public class Tickettypes  implements java.io.Serializable {


     private Integer typId;
     private String typOmschr;
     private double typPrijs;
     private Set ticketses = new HashSet(0);
     private Set tickettypesperfestivals = new HashSet(0);

    public Tickettypes() {
    }

	
    public Tickettypes(String typOmschr, double typPrijs) {
        this.typOmschr = typOmschr;
        this.typPrijs = typPrijs;
    }
    public Tickettypes(String typOmschr, double typPrijs, Set ticketses, Set tickettypesperfestivals) {
       this.typOmschr = typOmschr;
       this.typPrijs = typPrijs;
       this.ticketses = ticketses;
       this.tickettypesperfestivals = tickettypesperfestivals;
    }
   
    public Integer getTypId() {
        return this.typId;
    }
    
    public void setTypId(Integer typId) {
        this.typId = typId;
    }
    public String getTypOmschr() {
        return this.typOmschr;
    }
    
    public void setTypOmschr(String typOmschr) {
        this.typOmschr = typOmschr;
    }
    public double getTypPrijs() {
        return this.typPrijs;
    }
    
    public void setTypPrijs(double typPrijs) {
        this.typPrijs = typPrijs;
    }
    public Set getTicketses() {
        return this.ticketses;
    }
    
    public void setTicketses(Set ticketses) {
        this.ticketses = ticketses;
    }
    public Set getTickettypesperfestivals() {
        return this.tickettypesperfestivals;
    }
    
    public void setTickettypesperfestivals(Set tickettypesperfestivals) {
        this.tickettypesperfestivals = tickettypesperfestivals;
    }




}


